### ISSUE TITLE
Load current wave?

### ISSUE THREAD

**Issue by vphantom** [Youka/Yutils#5]
Hello,

Thank you for sharing Yutils. Through forums, I found your [wav.lua](https://github.com/Youka/Yutils/blob/T1/tests/wav.lua) script which might provide the exact basis for what I'm trying to achieve: an Aegisub automation script that loops through every 100ms of the current audio project in order to create empty subtitles in a fresh new project by guessing the start/stop positions of each human speech section.  (I can then just merge/split where it was inaccurate.)  This means performing some kind of FFT on both channels in a loop, defining some thresholds for frequencies and min/max duration and... not much else, yet it could save me a full 33% of the time I invest creating subtitles from scratch.  If I succeed, I intend to contribute the script to the Aegisub community ASAP of course, because I'm likely not the only one creating new subtitles with it.

Is there any way integrated within Aegisub that we could access the currently loaded audio instead of loading an external WAV file?  If not, then the "cleanest" way might be to access the name of the current video file (I usually deal with MP4) and run shell commands to extract audio from it using ffmpeg, then use `Yutils.decode.create_wav_reader()`?

I figure coming to you first might save me a lot of headaches looking in the wrong directions, especially as this will be my first attempt at speaking Lua. :smiley:

Thank you for your time!

**Comment by Youka** [comment]
I didn't look into Aegisub Dev for a year, so i don't know this functionality exists in their current API, but your thought about extracting audio and then decode by Yutils is a good way. Aegisub Lua has the function [aegisub.decode_path](http://docs.aegisub.org/3.2/Automation/Lua/Miscellaneous_APIs/#aegisubdecodepath) with [specifier ?video](http://docs.aegisub.org/3.2/Aegisub_path_specifiers/), so you get to the loaded video file, the rest you explained already.
But don't think it's easy to detect human speech.

**Comment by vphantom** [comment]
Thank you.  No doubt it would be difficult, but some of the videos I'm subtitling have near-silence between bits of speech, so I have hope for at least those.  I will look into `?video` and `?audio` next time I muster the courage to dive into Lua.

I'm also looking into external VAD (Voice Activity Detection) software, a promising one being WebRTC's implementation.  I might not be able to integrate those directly with Aegisub however, but it could make a decent stand-alone pre-processing tool to generate an SRT template with empty strings.
